apiVersion: v1
kind: Service
metadata:
  name: movie-releases-frontend
  labels:
    name: movie-releases-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32101
  selector:
    name: movie-releases-frontend
  type: NodePort